controller_list:
  - name: fake_ur5_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5_arm_shoulder_pan_joint
      - ur5_arm_shoulder_lift_joint
      - ur5_arm_elbow_joint
      - ur5_arm_wrist_1_joint
      - ur5_arm_wrist_2_joint
      - ur5_arm_wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses per group
  - group: ur5_arm
    pose: home
  - group: gripper
    pose: open