# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ur5_arm_shoulder_pan_joint
    - ur5_arm_shoulder_lift_joint
    - ur5_arm_elbow_joint
    - ur5_arm_wrist_1_joint
    - ur5_arm_wrist_2_joint
    - ur5_arm_wrist_3_joint
    - ur5_arm_robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_arm_shoulder_pan_joint
      - ur5_arm_shoulder_lift_joint
      - ur5_arm_elbow_joint
      - ur5_arm_wrist_1_joint
      - ur5_arm_wrist_2_joint
      - ur5_arm_wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotiq_85_left_knuckle_joint
ur5_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ur5_arm_shoulder_pan_joint
    - ur5_arm_shoulder_lift_joint
    - ur5_arm_elbow_joint
    - ur5_arm_wrist_1_joint
    - ur5_arm_wrist_2_joint
    - ur5_arm_wrist_3_joint
  gains:
    ur5_arm_shoulder_pan_joint:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    ur5_arm_shoulder_lift_joint:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    ur5_arm_elbow_joint:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    ur5_arm_wrist_1_joint:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    ur5_arm_wrist_2_joint:
      p: 100
      d: 10
      i: 0.1
      i_clamp: 100
    ur5_arm_wrist_3_joint:
      p: 10
      d: 1
      i: 0.1
      i_clamp: 100
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint
  gains:
    robotiq_85_left_knuckle_joint:
      p: 40
      d: 0
      i: 0
      i_clamp: 1
