controller_list:
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur5_arm_shoulder_pan_joint
      - ur5_arm_shoulder_lift_joint
      - ur5_arm_elbow_joint
      - ur5_arm_wrist_1_joint
      - ur5_arm_wrist_2_joint
      - ur5_arm_wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robotiq_85_left_knuckle_joint
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur5_arm_shoulder_pan_joint
      - ur5_arm_shoulder_lift_joint
      - ur5_arm_elbow_joint
      - ur5_arm_wrist_1_joint
      - ur5_arm_wrist_2_joint
      - ur5_arm_wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robotiq_85_left_knuckle_joint